// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaUDFtH6vpzSIeMTlRL2VidBzAC9lPDBQ',
    appId: '1:576996964089:web:c578687f3f201b059bd428',
    messagingSenderId: '576996964089',
    projectId: 'flutter-todo-2331d',
    authDomain: 'flutter-todo-2331d.firebaseapp.com',
    storageBucket: 'flutter-todo-2331d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG8TiCE7Uho-iF4ZWy940Y23KHjMrjZhA',
    appId: '1:576996964089:android:f6b2a92aeeac008e9bd428',
    messagingSenderId: '576996964089',
    projectId: 'flutter-todo-2331d',
    storageBucket: 'flutter-todo-2331d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo4Tfompo9ZiKxWhipLuzg00-wJf56-D0',
    appId: '1:576996964089:ios:b7696ee9fb2027679bd428',
    messagingSenderId: '576996964089',
    projectId: 'flutter-todo-2331d',
    storageBucket: 'flutter-todo-2331d.appspot.com',
    iosClientId: '576996964089-j766a6bniqcumef61ehe7m8cm8s4kq4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo4Tfompo9ZiKxWhipLuzg00-wJf56-D0',
    appId: '1:576996964089:ios:b7696ee9fb2027679bd428',
    messagingSenderId: '576996964089',
    projectId: 'flutter-todo-2331d',
    storageBucket: 'flutter-todo-2331d.appspot.com',
    iosClientId: '576996964089-j766a6bniqcumef61ehe7m8cm8s4kq4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase',
  );
}
